name: Release

on:
  workflow_dispatch:

jobs:
  release:
    name: Build release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: linux
          - os: macos-latest
            name: osx
          - os: windows-latest
            name: win
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - name: Setup
        uses: coursier/setup-action@v1
        with:
          jvm: "adoptium@1.17"
          apps: sbt
      - name: Package files
        run: sbt universal:packageBin
        shell: bash
      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: tripaint-${{matrix.name}}
          path: app/target/universal/
